export interface ProductItem {
  id: string;
  name: string;
  description: string;
  price: number; // Base (Regular) price
  prices?: {
    Regular: number;
    Medium: number;
    Large: number;
  };
  variants?: {
    name: string;
    price: number;
  }[];
  image: string;
  isVeg: boolean;
  badge?: string;
  categorySlug: string;
  isCustomizable?: boolean;
  inStock?: boolean;
}

export interface CategoryItem {
  id: string;
  name: string;
  slug: string;
  icon: string;
  sortOrder: number;
}

export interface BannerItem {
  id: string;
  title: string;
  subtitle: string;
  tag: string;
  badge: string;
  imageUrl: string;
}

export const INITIAL_BANNERS: BannerItem[] = [
  {
    id: 'banner-1',
    title: 'Tuesday Treat',
    subtitle: 'Medium Free with Large Pizza',
    tag: 'TUESDAY SPECIAL',
    badge: 'TUESDAYFREE',
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'banner-2',
    title: 'Funday Friday',
    subtitle: 'Buy 1 Get 1 Free on All Pizzas',
    tag: 'WEEKEND PARTY',
    badge: 'BOGOFRIDAY',
    imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'banner-3',
    title: '7Cheese Maxx Fiesta',
    subtitle: 'Cheesy Garlic Bread + 2 Pizzas @ ₹399',
    tag: 'COMBO DEAL',
    badge: 'CHEESE50',
    imageUrl: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&auto=format&fit=crop&q=80',
  },
];

export interface OfferItem {
  id: string;
  title: string;
  description: string;
  promoCode?: string;
  isActive: boolean;
  createdAt: string;
}

export const INITIAL_OFFERS: OfferItem[] = [
  {
    id: 'off-1',
    title: 'Funday Friday',
    description: 'Buy 1 Get 1 Free on Medium & Large Pizzas',
    promoCode: 'BOGOFRIDAY',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'off-2',
    title: 'Flat ₹100 OFF',
    description: 'Get flat ₹100 instant discount on all orders above ₹499',
    promoCode: 'CHEESE100',
    isActive: true,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'off-3',
    title: 'Free Cheesy Garlic Bread',
    description: 'Complimentary Garlic Breadsticks on cart total over ₹399',
    promoCode: 'FREEBREAD',
    isActive: false,
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
];

export const INITIAL_CATEGORIES: CategoryItem[] = [
  { id: 'cat-1', name: 'Veg Pizzas', slug: 'veg-pizzas', icon: '🍕', sortOrder: 1 },
  { id: 'cat-2', name: 'Non-Veg Pizzas', slug: 'non-veg-pizzas', icon: '🍗', sortOrder: 2 },
  { id: 'cat-3', name: 'Pan Pizzas', slug: 'pan-pizzas', icon: '🍳', sortOrder: 3 },
  { id: 'cat-4', name: 'Starters & Sides', slug: 'starters-sides', icon: '🥖', sortOrder: 4 },
  { id: 'cat-5', name: 'Burgers & Wraps', slug: 'burgers-wraps', icon: '🍔', sortOrder: 5 },
  { id: 'cat-6', name: 'Pasta & Chicken Corner', slug: 'pasta-chicken-corner', icon: '🍝', sortOrder: 6 },
  { id: 'cat-7', name: 'Desserts & Beverages', slug: 'desserts-beverages', icon: '🥤', sortOrder: 7 },
];

export const INITIAL_PRODUCTS: ProductItem[] = [
  // ==========================================
  // Category 1: Veg Pizzas (Sizes: Reg / Med / Lrg)
  // ==========================================
  {
    id: 'vp-baby-corn',
    name: 'Baby Corn',
    description: 'Tender sweet baby corn, crisp capsicum and extra loaded melted mozzarella',
    price: 269,
    prices: { Regular: 269, Medium: 449, Large: 599 },
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'New',
    categorySlug: 'veg-pizzas',
    isCustomizable: true,
  },
  {
    id: 'vp-deluxe-veggie',
    name: 'Deluxe Veggie',
    description: 'Onions, crisp capsicum, grilled mushroom, golden corn & spicy paneer cubes',
    price: 269,
    prices: { Regular: 269, Medium: 449, Large: 599 },
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Popular',
    categorySlug: 'veg-pizzas',
    isCustomizable: true,
  },
  {
    id: 'vp-veg-loaded',
    name: 'Veg Loaded',
    description: 'Tomato, jalapeno, crunchy bell peppers, black olives & sweet golden corn',
    price: 269,
    prices: { Regular: 269, Medium: 449, Large: 599 },
    image: 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'veg-pizzas',
    isCustomizable: true,
  },
  {
    id: 'vp-veg-supreme',
    name: 'Veg Supreme',
    description: 'Black olives, crisp capsicum, paneer chunks, red onions and sweet corn',
    price: 269,
    prices: { Regular: 269, Medium: 449, Large: 599 },
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Chef Special',
    categorySlug: 'veg-pizzas',
    isCustomizable: true,
  },
  {
    id: 'vp-peppy-paneer',
    name: 'Peppy Paneer',
    description: 'Flavorful trio of juicy paneer, crisp crunchy capsicum and spicy red paprika',
    price: 229,
    prices: { Regular: 229, Medium: 389, Large: 529 },
    image: 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Bestseller',
    categorySlug: 'veg-pizzas',
    isCustomizable: true,
  },
  {
    id: 'vp-schezwan-pizza',
    name: 'Schezwan Pizza',
    description: 'Fiery Schezwan sauce base loaded with veggies, mozzarella and herbs',
    price: 229,
    prices: { Regular: 229, Medium: 389, Large: 529 },
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Spicy',
    categorySlug: 'veg-pizzas',
    isCustomizable: true,
  },
  {
    id: 'vp-mexican-salsa',
    name: 'Mexican Salsa',
    description: 'Tangy Mexican salsa herbs, sweet corn, sliced jalapenos & crisp capsicum',
    price: 229,
    prices: { Regular: 229, Medium: 389, Large: 529 },
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'veg-pizzas',
    isCustomizable: true,
  },
  {
    id: 'vp-tandoori-veg',
    name: 'Tandoori Veg',
    description: 'Tandoori paneer, spiced onion, crunchy capsicum with smoky clay oven flavours',
    price: 229,
    prices: { Regular: 229, Medium: 389, Large: 529 },
    image: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'veg-pizzas',
    isCustomizable: true,
  },
  {
    id: 'vp-makhani-pizza',
    name: 'Makhani Pizza',
    description: 'Creamy rich butter makhani sauce with marinated paneer & capsicum',
    price: 229,
    prices: { Regular: 229, Medium: 389, Large: 529 },
    image: 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'veg-pizzas',
    isCustomizable: true,
  },
  {
    id: 'vp-spicy-tango',
    name: 'Spicy Tango',
    description: 'Red paprika, sweet corn, jalapenos and spicy peri-peri drizzle',
    price: 229,
    prices: { Regular: 229, Medium: 389, Large: 529 },
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'veg-pizzas',
    isCustomizable: true,
  },
  {
    id: 'vp-achari-pizza',
    name: 'Achari Pizza',
    description: 'Zesty Indian pickle spices infused with golden melted cheese & veggies',
    price: 229,
    prices: { Regular: 229, Medium: 389, Large: 529 },
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'veg-pizzas',
    isCustomizable: true,
  },
  {
    id: 'vp-double-cheese',
    name: 'Double Cheese',
    description: 'Double layer of 100% real dairy mozzarella cheese with herbs',
    price: 199,
    prices: { Regular: 199, Medium: 349, Large: 489 },
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Popular',
    categorySlug: 'veg-pizzas',
    isCustomizable: true,
  },
  {
    id: 'vp-farm-house',
    name: 'Farm House',
    description: 'Fresh capsicum, button mushrooms, sliced onions and ripe farm tomatoes',
    price: 199,
    prices: { Regular: 199, Medium: 349, Large: 489 },
    image: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Bestseller',
    categorySlug: 'veg-pizzas',
    isCustomizable: true,
  },
  {
    id: 'vp-country-special',
    name: 'Country Special',
    description: 'Crisp onion, capsicum, fresh juicy tomato slices and aromatic herbs',
    price: 199,
    prices: { Regular: 199, Medium: 349, Large: 489 },
    image: 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'veg-pizzas',
    isCustomizable: true,
  },
  {
    id: 'vp-pizza-paneer',
    name: 'Pizza Paneer',
    description: 'Generous pieces of fresh malai paneer over tomato herb sauce & cheese',
    price: 199,
    prices: { Regular: 199, Medium: 349, Large: 489 },
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'veg-pizzas',
    isCustomizable: true,
  },
  {
    id: 'vp-green-veg',
    name: 'Green Veg',
    description: 'Loaded with capsicum, jalapeno, black olives and garden greens',
    price: 199,
    prices: { Regular: 199, Medium: 349, Large: 489 },
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'veg-pizzas',
    isCustomizable: true,
  },
  {
    id: 'vp-margherita',
    name: 'Margherita',
    description: 'Classic delight with 100% real dairy mozzarella cheese on signature sauce',
    price: 119,
    prices: { Regular: 119, Medium: 229, Large: 349 },
    image: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'All-Time Fav',
    categorySlug: 'veg-pizzas',
    isCustomizable: true,
  },
  {
    id: 'vp-corn-cheese-pizza',
    name: 'Corn Cheese Pizza',
    description: 'Sweet juicy American golden corn kernels on thick layer of melted cheese',
    price: 119,
    prices: { Regular: 119, Medium: 229, Large: 349 },
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Kids Special',
    categorySlug: 'veg-pizzas',
    isCustomizable: true,
  },

  // ==========================================
  // Category 2: Non-Veg Pizzas (Sizes: Reg / Med / Lrg)
  // ==========================================
  {
    id: 'nvp-chicken-supremo',
    name: 'Chicken Supremo',
    description: 'Loaded with peri-peri chicken, chicken seekh kebab, chicken tikka & barbecue chicken',
    price: 329,
    prices: { Regular: 329, Medium: 469, Large: 629 },
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    badge: 'Meat Feast',
    categorySlug: 'non-veg-pizzas',
    isCustomizable: true,
  },
  {
    id: 'nvp-chicken-pepperoni',
    name: 'Chicken Pepperoni',
    description: 'Smoky chicken pepperoni slices loaded atop 100% mozzarella cheese',
    price: 329,
    prices: { Regular: 329, Medium: 469, Large: 629 },
    image: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    badge: 'Bestseller',
    categorySlug: 'non-veg-pizzas',
    isCustomizable: true,
  },
  {
    id: 'nvp-chicken-golden-delight',
    name: 'Chicken Golden Delight',
    description: 'Grilled barbeque chicken, golden sweet corn and extra cheese indulgence',
    price: 329,
    prices: { Regular: 329, Medium: 469, Large: 629 },
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    badge: 'Popular',
    categorySlug: 'non-veg-pizzas',
    isCustomizable: true,
  },
  {
    id: 'nvp-baby-corn-non-veg',
    name: 'Baby Corn Non-Veg Pizza',
    description: 'Tender baby corn paired with spiced chicken chunks and bell peppers',
    price: 329,
    prices: { Regular: 329, Medium: 469, Large: 629 },
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    categorySlug: 'non-veg-pizzas',
    isCustomizable: true,
  },
  {
    id: 'nvp-mexican-barbeque',
    name: 'Mexican Barbeque',
    description: 'Smoky BBQ chicken with jalapenos, onions, salsa herbs and mozzarella',
    price: 269,
    prices: { Regular: 269, Medium: 449, Large: 599 },
    image: 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    categorySlug: 'non-veg-pizzas',
    isCustomizable: true,
  },
  {
    id: 'nvp-chicken-seekh-kabab',
    name: 'Chicken Seekh Kabab',
    description: 'Mouthwatering chicken seekh slices with Indian tandoori spices and herbs',
    price: 269,
    prices: { Regular: 269, Medium: 449, Large: 599 },
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    categorySlug: 'non-veg-pizzas',
    isCustomizable: true,
  },
  {
    id: 'nvp-schezwan-chicken',
    name: 'Schezwan Chicken',
    description: 'Fiery Schezwan tossed chicken morsels with capsicum and red paprika',
    price: 269,
    prices: { Regular: 269, Medium: 449, Large: 599 },
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    badge: 'Spicy',
    categorySlug: 'non-veg-pizzas',
    isCustomizable: true,
  },
  {
    id: 'nvp-hot-hippy',
    name: 'Hot Hippy',
    description: 'Peri-peri spiced chicken, sliced red peppers, jalapenos and hot herbs',
    price: 269,
    prices: { Regular: 269, Medium: 449, Large: 599 },
    image: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    categorySlug: 'non-veg-pizzas',
    isCustomizable: true,
  },
  {
    id: 'nvp-peri-peri-chicken',
    name: 'Peri-Peri Chicken',
    description: 'Zesty peri-peri chicken chunks with crisp capsicum and onions',
    price: 269,
    prices: { Regular: 269, Medium: 449, Large: 599 },
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    categorySlug: 'non-veg-pizzas',
    isCustomizable: true,
  },
  {
    id: 'nvp-achari-non-veg',
    name: 'Achari Non-Veg Pizza',
    description: 'Spiced chicken marinated with authentic pickle masala & melted cheese',
    price: 269,
    prices: { Regular: 269, Medium: 449, Large: 599 },
    image: 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    categorySlug: 'non-veg-pizzas',
    isCustomizable: true,
  },
  {
    id: 'nvp-pineapple-salami-non-veg',
    name: 'Pineapple Salami Non-Veg',
    description: 'Hawaiian style chicken salami paired with sweet juicy pineapple & cheese',
    price: 269,
    prices: { Regular: 269, Medium: 449, Large: 599 },
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    categorySlug: 'non-veg-pizzas',
    isCustomizable: true,
  },
  {
    id: 'nvp-chicken-salami',
    name: 'Chicken Salami',
    description: 'Classic sliced chicken salami layered on rich herb sauce and cheese',
    price: 229,
    prices: { Regular: 229, Medium: 389, Large: 529 },
    image: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    categorySlug: 'non-veg-pizzas',
    isCustomizable: true,
  },
  {
    id: 'nvp-chicken-tikka',
    name: 'Chicken Tikka',
    description: 'Juicy tandoori chicken tikka pieces, crisp red onions and green capsicum',
    price: 229,
    prices: { Regular: 229, Medium: 389, Large: 529 },
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    badge: 'Popular',
    categorySlug: 'non-veg-pizzas',
    isCustomizable: true,
  },
  {
    id: 'nvp-chicken-fiesta',
    name: 'Chicken Fiesta',
    description: 'Barbeque chicken, juicy spiced chicken chunks with sweet corn and herbs',
    price: 229,
    prices: { Regular: 229, Medium: 389, Large: 529 },
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    categorySlug: 'non-veg-pizzas',
    isCustomizable: true,
  },
  {
    id: 'nvp-tandoori-chicken',
    name: 'Tandoori Chicken',
    description: 'Clay-oven style tandoori spiced chicken, green capsicum and onions',
    price: 229,
    prices: { Regular: 229, Medium: 389, Large: 529 },
    image: 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    badge: 'Bestseller',
    categorySlug: 'non-veg-pizzas',
    isCustomizable: true,
  },
  {
    id: 'nvp-barbeque-chicken',
    name: 'Barbeque Chicken',
    description: 'Classic American BBQ tossed chicken with crisp sliced onions and mozzarella',
    price: 199,
    prices: { Regular: 199, Medium: 349, Large: 489 },
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    categorySlug: 'non-veg-pizzas',
    isCustomizable: true,
  },
  {
    id: 'nvp-onion-spicy-chicken',
    name: 'Onion Spicy Chicken',
    description: 'Spicy chicken cubes paired with crunchy sliced onions and cheese',
    price: 199,
    prices: { Regular: 199, Medium: 349, Large: 489 },
    image: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    categorySlug: 'non-veg-pizzas',
    isCustomizable: true,
  },

  // ==========================================
  // Category 3: Pan Pizzas (Single Size)
  // ==========================================
  {
    id: 'pp-pan-paneer',
    name: 'Pan Paneer',
    description: 'Thick, crispy golden-crust pan pizza topped with fresh paneer & cheese',
    price: 119,
    image: 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'pan-pizzas',
  },
  {
    id: 'pp-pan-corn',
    name: 'Pan Corn',
    description: 'Crisp buttery pan crust loaded with sweet golden corn and mozzarella',
    price: 109,
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'pan-pizzas',
  },
  {
    id: 'pp-pan-onion',
    name: 'Pan Onion',
    description: 'Crunchy sliced onions on deep-pan golden baked crust with melted cheese',
    price: 99,
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'pan-pizzas',
  },
  {
    id: 'pp-pan-capsicum',
    name: 'Pan Capsicum',
    description: 'Crisp green capsicum rings on deep golden pan base with herb sauce',
    price: 99,
    image: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'pan-pizzas',
  },
  {
    id: 'pp-pan-tomato',
    name: 'Pan Tomato',
    description: 'Fresh ripe farm tomatoes with aromatic herbs and melted cheese',
    price: 99,
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'pan-pizzas',
  },
  {
    id: 'pp-pan-barbeque',
    name: 'Pan Barbeque',
    description: 'Deep-pan crust loaded with smoky BBQ chicken and melted mozzarella',
    price: 149,
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    badge: 'Popular',
    categorySlug: 'pan-pizzas',
  },
  {
    id: 'pp-pan-spicy',
    name: 'Pan Spicy',
    description: 'Spiced non-veg chicken morsels on thick fluffy pan base with cheese',
    price: 149,
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    categorySlug: 'pan-pizzas',
  },
  {
    id: 'pp-pan-tandoori',
    name: 'Pan Tandoori',
    description: 'Tandoori spiced chicken on signature deep-pan baked pizza crust',
    price: 149,
    image: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    categorySlug: 'pan-pizzas',
  },

  // ==========================================
  // Category 4: Starters & Sides (Veg / Non-Veg)
  // ==========================================
  {
    id: 'ss-classic-stuffed-gb-veg',
    name: 'Classic Stuffed Garlic Bread (Veg)',
    description: 'Freshly baked garlic bread stuffed with sweet corn, jalapenos & melted cheese',
    price: 129,
    image: 'https://images.unsplash.com/photo-1619881589148-c89b7b9015c7?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Bestseller',
    categorySlug: 'starters-sides',
  },
  {
    id: 'ss-classic-stuffed-gb-nv',
    name: 'Classic Stuffed Garlic Bread (Non-Veg)',
    description: 'Freshly baked garlic bread stuffed with chicken chunks, jalapenos & molten cheese',
    price: 150,
    image: 'https://images.unsplash.com/photo-1619881589148-c89b7b9015c7?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    categorySlug: 'starters-sides',
  },
  {
    id: 'ss-makhani-stuffed-gb-veg',
    name: 'Makhani Stuffed Garlic Bread (Veg)',
    description: 'Stuffed garlic bread with creamy makhani paneer filling and mozzarella',
    price: 129,
    image: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'starters-sides',
  },
  {
    id: 'ss-makhani-stuffed-gb-nv',
    name: 'Makhani Stuffed Garlic Bread (Non-Veg)',
    description: 'Stuffed garlic bread with rich makhani butter chicken filling and mozzarella',
    price: 150,
    image: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    categorySlug: 'starters-sides',
  },
  {
    id: 'ss-korean-sweet-chilli-gb-veg',
    name: 'Korean Sweet Chilli Stuffed Garlic Bread (Veg)',
    description: 'Sweet chilli glazed garlic loaf with cheesy vegetable stuffing',
    price: 129,
    image: 'https://images.unsplash.com/photo-1619881589148-c89b7b9015c7?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'starters-sides',
  },
  {
    id: 'ss-korean-sweet-chilli-gb-nv',
    name: 'Korean Sweet Chilli Stuffed Garlic Bread (Non-Veg)',
    description: 'Korean sweet chilli glazed garlic bread loaded with spicy chicken & cheese',
    price: 150,
    image: 'https://images.unsplash.com/photo-1619881589148-c89b7b9015c7?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    categorySlug: 'starters-sides',
  },
  {
    id: 'ss-korean-paneer-gb',
    name: 'Korean Paneer Stuffed Garlic Bread',
    description: 'Korean style glazed garlic bread with soft paneer chunks and molten cheese',
    price: 139,
    image: 'https://images.unsplash.com/photo-1619881589148-c89b7b9015c7?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'starters-sides',
  },
  {
    id: 'ss-taco-veg',
    name: 'Veg Taco',
    description: 'Crispy folded taco shell with spiced veg patty, salsa and cheese dip',
    price: 109,
    image: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'starters-sides',
  },
  {
    id: 'ss-taco-nv',
    name: 'Non-Veg Taco',
    description: 'Crispy folded taco shell with juicy spicy chicken filling, salsa and cheese',
    price: 129,
    image: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    badge: 'Popular',
    categorySlug: 'starters-sides',
  },
  {
    id: 'ss-spicy-cheese-pockets-veg',
    name: 'Spicy Cheese Pockets (Veg)',
    description: 'Golden crispy pocket bites bursting with hot molten spicy cheese',
    price: 99,
    image: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'starters-sides',
  },
  {
    id: 'ss-spicy-cheese-pockets-nv',
    name: 'Spicy Cheese Pockets (Non-Veg)',
    description: 'Crispy pocket bites stuffed with spiced chicken mince and molten cheese',
    price: 109,
    image: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    categorySlug: 'starters-sides',
  },
  {
    id: 'ss-cheese-bites',
    name: 'Cheese Bites',
    description: 'Bite-sized crumb-fried mozzarella balls served crisp and hot',
    price: 109,
    image: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'starters-sides',
  },
  {
    id: 'ss-zingy-parcel-veg',
    name: 'Zingy Parcel (Veg)',
    description: 'Snack parcel filled with seasoned paneer, creamy dressing & herbs',
    price: 69,
    image: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'starters-sides',
  },
  {
    id: 'ss-zingy-parcel-nv',
    name: 'Zingy Parcel (Non-Veg)',
    description: 'Snack parcel filled with seasoned spicy chicken, creamy dressing & herbs',
    price: 89,
    image: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    categorySlug: 'starters-sides',
  },
  {
    id: 'ss-garlic-bread',
    name: 'Garlic Bread (Veg)',
    description: 'Classic oven-toasted French baguette slices infused with herb garlic butter',
    price: 79,
    image: 'https://images.unsplash.com/photo-1619881589148-c89b7b9015c7?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'starters-sides',
  },
  {
    id: 'ss-salted-fries',
    name: 'Salted French Fries',
    description: 'Golden, crispy potato fries lightly sprinkled with sea salt',
    price: 79,
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'starters-sides',
  },
  {
    id: 'ss-peri-peri-fries',
    name: 'Peri Peri Fries',
    description: 'Crispy golden fries tossed in fiery African peri-peri spice mix',
    price: 89,
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Popular',
    categorySlug: 'starters-sides',
  },
  {
    id: 'dip-hot-garlic',
    name: 'Hot Garlic Dip',
    description: 'Zesty garlic and red chilli sauce dip (₹30)',
    price: 30,
    image: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'starters-sides',
  },
  {
    id: 'dip-cheese',
    name: 'Cheese Dip',
    description: 'Rich, velvety melted cheddar cheese dip (₹30)',
    price: 30,
    image: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'starters-sides',
  },
  {
    id: 'dip-schezwan',
    name: 'Schezwan Dip',
    description: 'Authentic Sichuan spicy dipping sauce (₹30)',
    price: 30,
    image: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'starters-sides',
  },
  {
    id: 'dip-honey-mustard',
    name: 'Honey Mustard Dip',
    description: 'Sweet and tangy honey mustard dressing dip (₹30)',
    price: 30,
    image: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'starters-sides',
  },

  // ==========================================
  // Category 5: Burgers & Wraps (Veg / Non-Veg)
  // ==========================================
  {
    id: 'bw-veg-burger',
    name: 'Veg Burger',
    description: 'Crisp vegetable patty with creamy mayo, lettuce and fresh tomato in toasted bun',
    price: 59,
    variants: [
      { name: 'Normal', price: 59 },
      { name: 'Premium', price: 79 },
    ],
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'burgers-wraps',
  },
  {
    id: 'bw-spicy-veg-burger',
    name: 'Spicy Veg Burger',
    description: 'Fiery spiced veggie patty with spicy relish, jalapenos and crunchy lettuce',
    price: 69,
    variants: [
      { name: 'Normal', price: 69 },
      { name: 'Premium', price: 89 },
    ],
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Spicy',
    categorySlug: 'burgers-wraps',
  },
  {
    id: 'bw-veg-double-patty-burger',
    name: 'Veg Double Patty Burger',
    description: 'Two crispy veg patties with double cheese slices, pickles and secret burger sauce',
    price: 89,
    variants: [
      { name: 'Normal', price: 89 },
      { name: 'Premium', price: 109 },
    ],
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'burgers-wraps',
  },
  {
    id: 'bw-non-veg-burger',
    name: 'Non-Veg Burger',
    description: 'Juicy crumb-fried chicken patty with herb mayo and crisp iceberg lettuce',
    price: 79,
    variants: [
      { name: 'Normal', price: 79 },
      { name: 'Premium', price: 99 },
    ],
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    badge: 'Popular',
    categorySlug: 'burgers-wraps',
  },
  {
    id: 'bw-non-veg-double-patty',
    name: 'Non-Veg Double Patty Burger',
    description: 'Double crunchy chicken patties with molten cheese layer and spicy mayo',
    price: 119,
    variants: [
      { name: 'Normal', price: 119 },
      { name: 'Premium', price: 139 },
    ],
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    categorySlug: 'burgers-wraps',
  },
  {
    id: 'bw-crispy-non-veg-burger',
    name: 'Crispy Non-Veg Burger',
    description: 'Extra crispy golden fried chicken breast fillet with creamy pepper mayo',
    price: 139,
    variants: [
      { name: 'Normal', price: 139 },
      { name: 'Premium', price: 159 },
    ],
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    badge: 'Chef Special',
    categorySlug: 'burgers-wraps',
  },
  {
    id: 'wrap-tandoori-veg',
    name: 'Tandoori Wrap (Veg)',
    description: 'Grilled tandoori paneer wrapped in soft tortilla with crunchy onions & mint mayo',
    price: 119,
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'burgers-wraps',
  },
  {
    id: 'wrap-tandoori-nv',
    name: 'Tandoori Wrap (Non-Veg)',
    description: 'Smoky clay-oven tandoori chicken wrapped with crisp onions & spicy mint dressing',
    price: 139,
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    badge: 'Popular',
    categorySlug: 'burgers-wraps',
  },
  {
    id: 'wrap-schezwan-veg',
    name: 'Schezwan Wrap (Veg)',
    description: 'Spicy Schezwan paneer cubes rolled with bell peppers and shredded veggies',
    price: 119,
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'burgers-wraps',
  },
  {
    id: 'wrap-schezwan-nv',
    name: 'Schezwan Wrap (Non-Veg)',
    description: 'Sichuan spiced chicken strips with crunchy onions in toasted tortilla',
    price: 139,
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    categorySlug: 'burgers-wraps',
  },
  {
    id: 'wrap-mexican-veg',
    name: 'Mexican Wrap (Veg)',
    description: 'Mexican spiced beans, sweet corn, salsa dressing and cheese with paneer',
    price: 119,
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'burgers-wraps',
  },
  {
    id: 'wrap-mexican-nv',
    name: 'Mexican Wrap (Non-Veg)',
    description: 'Mexican spiced chicken chunks, salsa dressing, sweet corn and jalapenos',
    price: 139,
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    categorySlug: 'burgers-wraps',
  },
  {
    id: 'wrap-makhani-veg',
    name: 'Makhani Wrap (Veg)',
    description: 'Creamy butter makhani gravy with paneer cubes wrapped in warm flatbread',
    price: 119,
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'burgers-wraps',
  },
  {
    id: 'wrap-makhani-nv',
    name: 'Makhani Wrap (Non-Veg)',
    description: 'Rich butter chicken makhani pieces wrapped in warm soft tortilla',
    price: 139,
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    categorySlug: 'burgers-wraps',
  },
  {
    id: 'wrap-hot-chili-garlic-veg',
    name: 'Hot Chili Garlic Wrap (Veg)',
    description: 'Fiery chili garlic paneer filling with crisp capsicum and spicy mayo',
    price: 119,
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'burgers-wraps',
  },
  {
    id: 'wrap-hot-chili-garlic-nv',
    name: 'Hot Chili Garlic Wrap (Non-Veg)',
    description: 'Hot garlic tossed chicken bites rolled with lettuce and crunchy peppers',
    price: 139,
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    categorySlug: 'burgers-wraps',
  },
  {
    id: 'wrap-barbeque-veg',
    name: 'Barbeque Wrap (Veg)',
    description: 'Smoky BBQ glazed paneer, sliced red onions and melted cheese wrap',
    price: 119,
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'burgers-wraps',
  },
  {
    id: 'wrap-barbeque-nv',
    name: 'Barbeque Wrap (Non-Veg)',
    description: 'Smoky American BBQ chicken with caramelized onions & cheese in flatbread',
    price: 139,
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    categorySlug: 'burgers-wraps',
  },
  {
    id: 'wrap-chipotle-veg',
    name: 'Chipotle Wrap (Veg)',
    description: 'Smoky Mexican chipotle sauce, paneer, sweet corn & crispy salad',
    price: 119,
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'burgers-wraps',
  },
  {
    id: 'wrap-chipotle-nv',
    name: 'Chipotle Wrap (Non-Veg)',
    description: 'Chipotle spiced chicken chunks, bell peppers and melted cheese wrap',
    price: 139,
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    categorySlug: 'burgers-wraps',
  },
  {
    id: 'wrap-achari-veg',
    name: 'Achari Wrap (Veg)',
    description: 'Pickle spiced tangy paneer rolled with onions and mint yogurt spread',
    price: 119,
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'burgers-wraps',
  },
  {
    id: 'wrap-achari-nv',
    name: 'Achari Wrap (Non-Veg)',
    description: 'Tangy achari spiced chicken rolled with crunchy onion rings and herbs',
    price: 139,
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    categorySlug: 'burgers-wraps',
  },
  {
    id: 'wrap-chicken-tikka',
    name: 'Chicken Tikka Wrap',
    description: 'Succulent roasted chicken tikka pieces in signature cream and herb dressing',
    price: 139,
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    badge: 'Bestseller',
    categorySlug: 'burgers-wraps',
  },

  // ==========================================
  // Category 6: Pasta & Chicken Corner
  // ==========================================
  {
    id: 'pasta-makhani-veg',
    name: 'Makhani Sauce Pasta (Veg)',
    description: 'Penne pasta tossed in rich velvety Indian butter makhani sauce with veggies',
    price: 120,
    image: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281699?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'pasta-chicken-corner',
  },
  {
    id: 'pasta-makhani-nv',
    name: 'Makhani Sauce Pasta (Non-Veg)',
    description: 'Penne pasta in rich butter makhani sauce loaded with tender chicken pieces',
    price: 140,
    image: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281699?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    categorySlug: 'pasta-chicken-corner',
  },
  {
    id: 'pasta-mix-veg',
    name: 'Mix Sauce Pasta (Veg)',
    description: 'Penne pasta in perfect blend of creamy white and tangy red arrabbiata sauce',
    price: 120,
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Popular',
    categorySlug: 'pasta-chicken-corner',
  },
  {
    id: 'pasta-mix-nv',
    name: 'Mix Sauce Pasta (Non-Veg)',
    description: 'Penne pasta in luscious pink sauce tossed with spiced chicken & herbs',
    price: 140,
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    categorySlug: 'pasta-chicken-corner',
  },
  {
    id: 'pasta-red-veg',
    name: 'Red Sauce Arrabbiata (Veg)',
    description: 'Italian penne in spiced tomato basil sauce with capsicum, olives & herbs',
    price: 100,
    image: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281699?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'pasta-chicken-corner',
  },
  {
    id: 'pasta-red-nv',
    name: 'Red Sauce Arrabbiata (Non-Veg)',
    description: 'Penne in zesty red tomato basil sauce with grilled chicken chunks',
    price: 120,
    image: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281699?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    categorySlug: 'pasta-chicken-corner',
  },
  {
    id: 'pasta-white-veg',
    name: 'White Sauce Alfredo (Veg)',
    description: 'Creamy rich cheesy Alfredo sauce pasta with sweet corn & sliced mushrooms',
    price: 100,
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Bestseller',
    categorySlug: 'pasta-chicken-corner',
  },
  {
    id: 'pasta-white-nv',
    name: 'White Sauce Alfredo (Non-Veg)',
    description: 'Indulgent white cream cheese Alfredo pasta loaded with seasoned chicken',
    price: 120,
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    categorySlug: 'pasta-chicken-corner',
  },
  {
    id: 'chk-hot-wings',
    name: 'Chicken Hot Wings',
    description: 'Crispy fried chicken wings glazed with hot & spicy barbecue sauce',
    price: 99,
    variants: [
      { name: '2 Pieces', price: 99 },
      { name: '4 Pieces', price: 199 },
    ],
    image: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    badge: 'Spicy',
    categorySlug: 'pasta-chicken-corner',
  },
  {
    id: 'chk-boneless-fried',
    name: 'Boneless Fried Chicken (6pc)',
    description: 'Crispy tender boneless chicken strips fried till golden with dipping seasoning',
    price: 160,
    image: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    categorySlug: 'pasta-chicken-corner',
  },
  {
    id: 'chk-nuggets',
    name: 'Chicken Nuggets (8pc)',
    description: 'Classic bite-sized crumb-coated minced chicken nuggets with dip',
    price: 120,
    image: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=600&auto=format&fit=crop&q=80',
    isVeg: false,
    categorySlug: 'pasta-chicken-corner',
  },

  // ==========================================
  // Category 7: Desserts & Beverages
  // ==========================================
  {
    id: 'db-choco-lava',
    name: 'Choco Lava Cake',
    description: 'Decadent warm chocolate cake with a molten liquid fudge center',
    price: 119,
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Bestseller',
    categorySlug: 'desserts-beverages',
  },
  {
    id: 'db-shake-strawberry',
    name: 'Strawberry Shake',
    description: 'Creamy thick shake blended with strawberry puree and vanilla ice cream',
    price: 119,
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'desserts-beverages',
  },
  {
    id: 'db-shake-butterscotch',
    name: 'Butterscotch Shake',
    description: 'Rich butterscotch crunchy shake topped with caramel syrup',
    price: 119,
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'desserts-beverages',
  },
  {
    id: 'db-shake-chocolate',
    name: 'Chocolate Shake',
    description: 'Indulgent Belgian chocolate shake made with dairy milk & cocoa',
    price: 119,
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Popular',
    categorySlug: 'desserts-beverages',
  },
  {
    id: 'db-shake-mango',
    name: 'Mango Shake',
    description: 'Sweet Alphonso mango pulp blended into thick creamy shake',
    price: 119,
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'desserts-beverages',
  },
  {
    id: 'db-shake-vanilla',
    name: 'Vanilla Shake',
    description: 'Classic smooth French vanilla bean milkshake',
    price: 119,
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'desserts-beverages',
  },
  {
    id: 'db-shake-oreo',
    name: 'Oreo Shake',
    description: 'Crunchy crushed Oreo cookies whipped into chocolate cream shake',
    price: 119,
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Kids Fav',
    categorySlug: 'desserts-beverages',
  },
  {
    id: 'db-shake-kesar-mango',
    name: 'Kesar Mango Shake',
    description: 'Aromatic saffron infused with royal mango milk blend',
    price: 119,
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'desserts-beverages',
  },
  {
    id: 'db-shake-berry-gummy',
    name: 'Berry Gummy Shake',
    description: 'Wild berry blend with gummy chew surprises',
    price: 119,
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'desserts-beverages',
  },
  {
    id: 'db-shake-pineapple-coconut',
    name: 'Pineapple Coconut Shake',
    description: 'Tropical pina colada style milkshake with toasted coconut',
    price: 119,
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'desserts-beverages',
  },
  {
    id: 'db-shake-paan-pine',
    name: 'Paan Pine Shake',
    description: 'Refreshing sweet betel paan combined with pineapple essence',
    price: 119,
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'desserts-beverages',
  },
  {
    id: 'db-boba-blueberry',
    name: 'Blueberry Popping Boba',
    description: 'Refreshing iced fruit tea with juicy popping blueberry pearls',
    price: 150,
    image: 'https://images.unsplash.com/photo-1558857563-b37cfb4279b9?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Trending',
    categorySlug: 'desserts-beverages',
  },
  {
    id: 'db-boba-peach',
    name: 'Peach Popping Boba',
    description: 'Sweet iced peach tea filled with burst-in-mouth boba pearls',
    price: 140,
    image: 'https://images.unsplash.com/photo-1558857563-b37cfb4279b9?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'desserts-beverages',
  },
  {
    id: 'db-boba-strawberry',
    name: 'Strawberry Popping Boba',
    description: 'Chilled strawberry iced nectar with strawberry juice pearls',
    price: 140,
    image: 'https://images.unsplash.com/photo-1558857563-b37cfb4279b9?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'desserts-beverages',
  },
  {
    id: 'db-boba-mango',
    name: 'Mango Popping Boba',
    description: 'Tropical mango iced refreshment filled with popping juice pearls',
    price: 140,
    image: 'https://images.unsplash.com/photo-1558857563-b37cfb4279b9?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'desserts-beverages',
  },
  {
    id: 'db-mocktail-blueberry',
    name: 'Blueberry Mocktail',
    description: 'Sparkling cooler with crushed blueberries, fresh mint and lime',
    price: 139,
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'desserts-beverages',
  },
  {
    id: 'db-mocktail-virgin-mojito',
    name: 'Virgin Mojito',
    description: 'Classic blend of crushed mint leaves, fresh lime juice and chilled soda',
    price: 129,
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Popular',
    categorySlug: 'desserts-beverages',
  },
  {
    id: 'db-mocktail-strawberry-watermelon',
    name: 'Strawberry Watermelon Mocktail',
    description: 'Refreshing thirst quencher with juicy strawberry and watermelon splash',
    price: 129,
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'desserts-beverages',
  },
  {
    id: 'db-mocktail-blue-lagoon',
    name: 'Blue Lagoon',
    description: 'Electric blue curacao citrus mocktail served chilled over ice',
    price: 129,
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'desserts-beverages',
  },
  {
    id: 'db-mocktail-masala-lemonade',
    name: 'Masala Lemonade',
    description: 'Zesty Indian spiced shikanji lemonade with roasted cumin and black salt',
    price: 129,
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'desserts-beverages',
  },
  {
    id: 'db-coffee-classic',
    name: 'Classic Cold Coffee',
    description: 'Rich brewed espresso blended with chilled milk and sweetened cream',
    price: 109,
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Popular',
    categorySlug: 'desserts-beverages',
  },
  {
    id: 'db-coffee-hazelnut',
    name: 'Hazelnut Cold Coffee',
    description: 'Espresso cold coffee infused with roasted nutty hazelnut syrup',
    price: 119,
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'desserts-beverages',
  },
  {
    id: 'db-coffee-irish',
    name: 'Irish Cold Coffee',
    description: 'Creamy cold brew flavored with rich non-alcoholic Irish cream syrup',
    price: 119,
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'desserts-beverages',
  },
  {
    id: 'db-coffee-caramel',
    name: 'Caramel Cold Coffee',
    description: 'Creamy cold coffee drizzled with golden salted caramel sauce',
    price: 119,
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'desserts-beverages',
  },
  {
    id: 'db-coffee-chocolate-frappe',
    name: 'Chocolate Frappe',
    description: 'Thick blended coffee frappe with melted dark chocolate swirl',
    price: 119,
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'desserts-beverages',
  },
  {
    id: 'db-icetea-peach',
    name: 'Peach Ice Tea',
    description: 'Chilled steeped black tea infused with sweet peach nectar',
    price: 89,
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'desserts-beverages',
  },
  {
    id: 'db-icetea-lemon',
    name: 'Lemon Ice Tea',
    description: 'Classic refreshing chilled lemon iced tea with mint sprig',
    price: 89,
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'desserts-beverages',
  },
  {
    id: 'db-buransh',
    name: 'Buransh Cooler',
    description: 'Himalayan wild Rhododendron (Buransh) nectar with natural healing zest',
    price: 109,
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    badge: 'Haldwani Special',
    categorySlug: 'desserts-beverages',
  },
  {
    id: 'db-fresh-lime-soda',
    name: 'Fresh Lime Soda',
    description: 'Refreshing sparkling soda squeezed with fresh yellow lemons (Sweet / Salt)',
    price: 70,
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80',
    isVeg: true,
    categorySlug: 'desserts-beverages',
  },
];
